# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TermRex < Formula
  desc "A terminal-based dinosaur runner game inspired by Chrome's offline game"
  homepage "https://github.com/jianongHe/term-rex"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jianongHe/Term-Rex/releases/download/v0.1.3/term-rex_0.1.3_darwin_amd64.tar.gz"
      sha256 "1f13a038e09d09e1b8d76a7707a51264215db2690396abfedb6468a764bc759c"

      def install
        bin.install "term-rex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jianongHe/Term-Rex/releases/download/v0.1.3/term-rex_0.1.3_darwin_arm64.tar.gz"
      sha256 "5598dd1db9f0b71b2d8159f54d0f77f647c002235a30001d1ae93f1821c270ed"

      def install
        bin.install "term-rex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/jianongHe/Term-Rex/releases/download/v0.1.3/term-rex_0.1.3_linux_amd64.tar.gz"
      sha256 "b7d0e1b656c8888588e1ec516b6dcd3be835a3e7018f245da943726464a5a9a5"
      def install
        bin.install "term-rex"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/jianongHe/Term-Rex/releases/download/v0.1.3/term-rex_0.1.3_linux_arm64.tar.gz"
      sha256 "473445e99d3f85df1d67285efe0089b3fd6be2224e1f33be73fe745e09749b8a"
      def install
        bin.install "term-rex"
      end
    end
  end

  test do
    system "#{bin}/term-rex --version"
  end
end
