# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TermRex < Formula
  desc "A terminal-based dinosaur runner game inspired by Chrome's offline game"
  homepage "https://github.com/jianongHe/term-rex"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jianongHe/Term-Rex/releases/download/v0.1.6/term-rex_0.1.6_darwin_amd64.tar.gz"
      sha256 "aea26fa67540aefe5665d5f9e707adf755b85de06a0219d360ff072869b53f54"

      def install
        bin.install "term-rex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jianongHe/Term-Rex/releases/download/v0.1.6/term-rex_0.1.6_darwin_arm64.tar.gz"
      sha256 "6635da7cd2ba7b66e3a915ee40bc619151d5d1f46bf7f5700cd3e7d4696333ab"

      def install
        bin.install "term-rex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/jianongHe/Term-Rex/releases/download/v0.1.6/term-rex_0.1.6_linux_amd64.tar.gz"
      sha256 "de15135ef0c9e0fd6a07f78a65df4d9072020d967abb0781e6d69718310d5ea4"
      def install
        bin.install "term-rex"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/jianongHe/Term-Rex/releases/download/v0.1.6/term-rex_0.1.6_linux_arm64.tar.gz"
      sha256 "e2c2255055c8d6b2ec29596657a918c0229691e4654564e472c2f8ee38d03e58"
      def install
        bin.install "term-rex"
      end
    end
  end

  test do
    system "#{bin}/term-rex --version"
  end
end
