# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TermRex < Formula
  desc "A terminal-based dinosaur runner game inspired by Chrome's offline game"
  homepage "https://github.com/jianongHe/term-rex"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jianongHe/Term-Rex/releases/download/v0.1.7/term-rex_0.1.7_darwin_amd64.tar.gz"
      sha256 "cac418b76f15dd96d4b2622ed575718b4d10699d0277dea37c1f73538b1082b0"

      def install
        bin.install "term-rex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jianongHe/Term-Rex/releases/download/v0.1.7/term-rex_0.1.7_darwin_arm64.tar.gz"
      sha256 "a0ffe7454e359209f51653c81b6d0db4fa1068a39e7678947618bd29b370cdf3"

      def install
        bin.install "term-rex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/jianongHe/Term-Rex/releases/download/v0.1.7/term-rex_0.1.7_linux_amd64.tar.gz"
      sha256 "b775b9e0db8a37778f08321071837888e3758b4fe58e241a0c7a7e84749250a1"
      def install
        bin.install "term-rex"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/jianongHe/Term-Rex/releases/download/v0.1.7/term-rex_0.1.7_linux_arm64.tar.gz"
      sha256 "cdcb8dbb6444da675638ede76ad80a1f114246290e994c0a13c2872e0cf318ef"
      def install
        bin.install "term-rex"
      end
    end
  end

  test do
    system "#{bin}/term-rex --version"
  end
end
